[package]
name = "server"
version = "0.1.0"
authors = ["Andrew Torres <andrew.jonathan.torres@gmail.com>"]
edition = "2018"
description = "Web server in charge of orchestrating business logic interactions"
documentation = "https://github.com/ajtorres9/forge/wiki"
readme = "readme.md"
homepage = "https://github.com/ajtorres9/forge#readme"
repository = "https://github.com/ajtorres9/forge/tree/master/packages/server"
license = "MIT"
keywords = ["graphql", "postgresql", "rust", "web-server"]
publish = false

[dependencies]
actix-cors = "^0.5.3"
actix-rt = "^1.1.1"
dotenv = "^0.15.0"
env_logger = "^0.8.2"
juniper = "^0.14.2"
log = "^0.4.11"
r2d2 = "^0.8.9"
serde_derive = "^1.0.105"
serde_json = "^1.0.60"
structopt = "^0.3.21"

[dependencies.actix-web]
version = "^3.3.2"
default-features = false

[dependencies.chrono]
version = "^0.4.19"
default-features = false
features = ["clock", "serde", "std"]

[dependencies.diesel]
version = "^1.4.5"
default-features = false
features = ["32-column-tables", "chrono", "postgres", "r2d2", "uuidv07"]

[dependencies.serde]
version = "^1.0.117"
default-features = false
features = ["std", "derive"]

[dependencies.uuid]
version = "0.7.4"
default-features = false
features = ["serde", "std", "v4"]
